#!/usr/bin/env python3
"""
Generate the full winmm export surface for the proxy DLL.

Once BetterFlight is loaded as "winmm.dll", EVERY module in the game process that
imports winmm binds to it - Steam's client DLL, overlays, frame-generation DLLs -
not just NMS.exe. Windows refuses to start the game if any imported name is
missing (Wine only logs it). So the proxy exports the union of:

  reference/winmm_windows_*.exports   real Windows 10/11 winmm.dll (from Microsoft's
                                       symbol server via winbindex)
  reference/winmm_wine_*.exports      Wine/Proton's builtin winmm.dll

Ordinals follow Windows 11 24H2 (identical to Windows 10 22H2), including its
unnamed ordinal-only export; names only found elsewhere follow after.

Writes src/winmm_exports.inc and src/winmm.def.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REF  = HERE / "reference"


ORDINAL_SOURCE = "winmm_windows_11-24H2.exports"


def read(path):
    """[(ordinal, name or None)]"""
    rows = []
    for line in path.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].isdigit():
            rows.append((int(parts[0]), None if parts[1] == "-" else parts[1]))
    return rows


def main():
    win = sorted(REF.glob("winmm_windows_*.exports"))
    wine = sorted(REF.glob("winmm_wine_*.exports"))
    src = REF / ORDINAL_SOURCE
    if not src.exists():
        raise SystemExit(f"missing {src}")

    ordered = sorted(read(src))                       # [(ordinal, name|None)]
    have = {n for _, n in ordered if n}
    extra = sorted({n for p in win + wine for _, n in read(p) if n} - have)
    nxt = max(o for o, _ in ordered) + 1
    for n in extra:
        ordered.append((nxt, n)); nxt += 1

    bad = [n for _, n in ordered if n and not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n)]
    if bad:
        raise SystemExit(f"non-identifier export names: {bad}")
    needed = REF / "winmm_imported_by_game_folder.txt"
    if needed.exists():
        missing = {l.strip() for l in needed.read_text().splitlines() if l.strip()} - have - set(extra)
        if missing:
            raise SystemExit(f"game-folder modules import names not in the export set: {sorted(missing)}")

    inc = ["/* GENERATED by gen_winmm_exports.py - do not edit. */"]
    df = ["; GENERATED by gen_winmm_exports.py - do not edit.", "LIBRARY winmm", "EXPORTS"]
    for i, (o, n) in enumerate(ordered):
        if n:
            inc.append(f"WINMM_EXPORT({i}, {n})")
            df.append(f"    {n} = bf_x_{n} @{o}")
        else:
            inc.append(f"WINMM_EXPORT_ORD({i}, {o})")
            df.append(f"    bf_x_ord_{o} @{o} NONAME")
    (HERE / "src" / "winmm_exports.inc").write_text("\n".join(inc) + "\n")
    (HERE / "src" / "winmm.def").write_text("\n".join(df) + "\n")

    unnamed = sum(1 for _, n in ordered if not n)
    print(f"winmm exports: {len(ordered)} ({len(ordered) - unnamed} named, {unnamed} ordinal-only); "
          f"ordinals from {ORDINAL_SOURCE}, {len(extra)} extra names from other builds/Wine")


if __name__ == "__main__":
    main()
