#!/usr/bin/env python3
"""
Generate src/flight_tuning.inc from the tuning tables in build_mod.py.

Since 1.2.0 the DLL applies the flight retune in memory instead of shipping a
replacement GCSPACESHIPGLOBALS.GLOBAL.MBIN. build_mod.py stays the single
source of truth for WHAT changes; this turns its tables into C:

    BF_ENGINE_TUNE_ALWAYS("SpaceEngine", "MinSpeed", BF_SET, 0.0f)
    BF_ENGINE_TUNE("SpaceEngine", "DirectionBrake", BF_MUL, 0.1f)
    BF_GLOBAL_TUNE("LinearDamping", BF_SET, 0.0f)

Engine entries apply to every GcPlayerSpaceshipControlData block the game has
(Control, ControlLight, ControlCorvette, ...), found at runtime.

TUNE_ALWAYS entries apply in both flight modes (coupled and decoupled);
TUNE entries apply in decoupled mode only - in coupled mode the game's loaded
values are left in place (or restored) for those fields.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import build_mod as BM  # noqa: E402


def op(spec):
    if isinstance(spec, tuple) and spec[0] == "mul":
        return "BF_MUL", float(spec[1])
    return "BF_SET", float(spec)


lines = ["/* Generated by gen_tuning.py from build_mod.py - do not edit. */"]
for engine, fields in BM.ALWAYS_ENGINE_TUNING.items():
    for field, spec in fields.items():
        o, v = op(spec)
        lines.append(f'BF_ENGINE_TUNE_ALWAYS("{engine}", "{field}", {o}, {v!r}f)')
for engine, fields in BM.ENGINE_TUNING.items():
    for field, spec in fields.items():
        o, v = op(spec)
        lines.append(f'BF_ENGINE_TUNE("{engine}", "{field}", {o}, {v!r}f)')
for field, spec in BM.GLOBAL_TUNING.items():
    o, v = op(spec)
    lines.append(f'BF_GLOBAL_TUNE("{field}", {o}, {v!r}f)')

out = HERE / "src" / "flight_tuning.inc"
text = "\n".join(lines) + "\n"
if not out.exists() or out.read_text() != text:
    out.write_text(text)
n_always = sum(len(f) for f in BM.ALWAYS_ENGINE_TUNING.values())
n_engine = sum(len(f) for f in BM.ENGINE_TUNING.values())
print(f"flight tuning: {n_always} always + {n_engine} decoupled-only engine fields x every control block, "
      f"{len(BM.GLOBAL_TUNING)} decoupled-only globals -> {out.name}")
